### PR TITLE
Fixed #96

### LINKED ISSUE #96: [BUG]: Crash on MC:BE v1.20.30
If you use the newest PocketMine-MP version (5.6.0) for MC:BE v1.20.30 CPlot will crash on server startup-

https://crash.pmmp.io/view/9257874

### PR DESCRIPTION
**Pull request by supercrafter333**

### CODE REVIEW

File: src/ColinHDev/CPlot/utils/ParseUtils.php [hunk 1]
```diff
@@ -163,4 +163,4 @@ public static function parseMyPlotBlock(array $array, string | int $key) : ?Bloc
         }
         return null;
 	}
-}
\ No newline at end of file
+}
```
Comment (ColinHDev) [inline src/ColinHDev/CPlot/utils/ParseUtils.php]: Please don't include these unnecessary changes.

File: src/ColinHDev/CPlot/utils/ParseUtils.php [hunk 2]
```diff
@@ -109,7 +109,7 @@ private static function parseBlockFromCompressedTreeRoot(string $compressedTreeR
             return null;
         }
         try {
-            $blockState = BlockStateData::fromNbt($compoundTag);
+            $blockState = GlobalBlockStateHandlers::getUpgrader()->upgradeBlockStateNbt($compoundTag);
         } catch (BlockStateDeserializeException) {
             return null;
         }
```
Comment (ColinHDev) [inline src/ColinHDev/CPlot/utils/ParseUtils.php:115]:
```suggestion
        try {
            $blockState = BlockStateData::fromNbt($compoundTag);
        } catch (BlockStateDeserializeException) {
            return null;
        }
        $blockState = GlobalBlockStateHandlers::getUpgrader()->getBlockStateUpgrader()->upgrade($blockState);
```
Might be better. 
The only difference between this way and `upgradeBlockStateNbt()` would be that `upgradeBlockStateNbt()` also checks if the compound tag is a pre-1.13 block state. And if I am not wrong, this should never be the case since CPlot deals with blocks consisting of ids and metas differently in other places. So by using `upgrade()` we can skip that step directly.

Comment (ColinHDev) [inline src/ColinHDev/CPlot/utils/ParseUtils.php:115]:
```suggestion
        try {
            $blockState = BlockStateData::fromNbt($compoundTag);
        } catch (BlockStateDeserializeException) {
            return null;
        }
        $blockState = GlobalBlockStateHandlers::getUpgrader()->getBlockStateUpgrader()->upgrade($blockState);
```
Might be better. 
The only difference between this way and `upgradeBlockStateNbt()` would be that `upgradeBlockStateNbt()` also checks if the compound tag is a pre-1.13 block state. And if I am not wrong, this should never be the case since CPlot deals with blocks consisting of ids and metas differently in other places. So by using `upgrade()` we can skip that step directly.
